### ISSUE TITLE
Revoke master on W-VET deploy

### ISSUE THREAD

**Issue by OliverNChalk** [vexchange/deployVexchange#3]
We added it for factory, we should also add it for W-VET as that is actually more important to ensure we are no the master there (otherwise we could steal VTHO dividends)

**Comment by xenide** [comment]
Okay done. Btw how are the users going to claim the VTHO associated with the WVET in a transparent way? Right now it's just the owner (us) who can make the transfers?

**Comment by OliverNChalk** [comment]
Yep, the idea is that you deposit to W-VET then into the pool. So we will just credit the pool (because the pool is the holder). So we will push VTHO, users won't pull it. Medium term we may introduce a server to generalize it (if we think users will hold outside of Vexchange). Long term we will make the owner a trustless contract that lets users claim from there
